apiVersion: v1
kind: Secret
metadata:
  name: blackbox-scrape-config
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
            - http://auth-service.sunil-restauranty-dev.svc.cluster.local:3001/health
            - http://discounts-service.sunil-restauranty-dev.svc.cluster.local:3002/health
            - http://items-service.sunil-restauranty-dev.svc.cluster.local:3003/health
            - http://client-service.sunil-restauranty-dev.svc.cluster.local/
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
