apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: sunil-restauranty-dev
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL21vbmdvLXNlcnZpY2Uuc3VuaWwtcmVzdGF1cmFudHktZGV2LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L3Jlc3RhdXJhbnR5
